### ISSUE TITLE
Indentation is always 2 spaces

### ISSUE THREAD

**Issue by Igor-Palaguta** [ruiaureliano/X-SwiftFormat#1]
Hello,

Great tool, thanks!

Installed version 0.9.2 used this configuration:

```json
{
  "maximumBlankLines" : 1,
  "indentation" : {
    "AAA" : 4
  }
}
```

But instead of 4 spaces it converts to 2 spaces. In preview it also uses 2 spaces

**Comment by ruiaureliano** [comment]
Why you have `AAA`: 4 ?? It should be `tabs` or `spaces`

**Comment by Igor-Palaguta** [comment]
Please check my settings

<img width="737" alt="Screenshot 2020-04-03 at 22 14 13" src="https://user-images.githubusercontent.com/800044/78396702-7d22e700-75f8-11ea-91e3-66d043ca324b.png">

**Comment by Igor-Palaguta** [comment]
Ahh probably I should set both?
<img width="739" alt="Screenshot 2020-04-03 at 22 15 36" src="https://user-images.githubusercontent.com/800044/78396812-aba0c200-75f8-11ea-8a8c-22dbc4060330.png">

**Comment by ruiaureliano** [comment]
Just found the issue will release 0.9.3 soon 💪

**Comment by Igor-Palaguta** [comment]
With same configuration it also breaks 100 character lines

**Comment by ruiaureliano** [comment]
Maybe this is not clear enough.

**1) Line Length** is active and is using the value of `200`
<img width="862" alt="Screenshot 2020-04-04 at 10 11 15" src="https://user-images.githubusercontent.com/435699/78423215-d7559380-765c-11ea-8b8b-f45f56d29fcc.png">

---

**2) Line Length** is not  active and is using the default value, which is `100`, but the text field says `200` because that's the value that you have

<img width="862" alt="Screenshot 2020-04-04 at 10 11 46" src="https://user-images.githubusercontent.com/435699/78423230-e4728280-765c-11ea-9125-bef023cbd863.png">
